FROM php:8.4-fpm-alpine

RUN apk add --no-cache \
    postgresql-dev \
    nodejs \
    npm \
    git \
    unzip \
    && docker-php-ext-install \
        pdo_pgsql \
        pgsql \
        pcntl \
        bcmath

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# En dev on monte le code source via volume, pas de COPY
# Composer install se fait via entrypoint ou manuellement

EXPOSE 9000

CMD ["php-fpm"]
